import subprocess
# ARI_consistency_test.py [-h] [--directory DIRECTORY] [--algo ALGO] [--iters ITERS] [--gamma GAMMA] [--clust CLUST] [--cutoff_last CUTOFF_LAST] [--cutoff_lastAccumulated CUTOFF_LASTACCUMULATED] [--batches BATCHES] [--trials TRIALS]
#                                [--test_runs TEST_RUNS] [--path PATH] [--accumulative] [--both] [--plot_everything] [--plot_lightly] [--real_time] [--normalize_lambda] [--log_scale_time] [--plot_on_log_scale] [--save_all]


subprocess.run(
    "python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 12 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 12 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 12 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 10 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 10 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 10 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 9  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 9  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 9  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 8  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 8  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 8  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 7  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 7  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 7  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 6  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 6  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --both --plot_lightly --save_all &\
     python3 ARI_consistency_test.py --directory 'msmc_curve_data_realtimeprocessed_and_interpolated/' --spec='interpolated' --suffix='.tsv' --sep='\t' --clust 6  --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --both --plot_lightly --save_all &",
     shell=True)
