import subprocess

subprocess.run(
    "python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust  7 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust  7 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust  7 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust  9 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust  9 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust  9 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust 12 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 10  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust 12 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 40  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &\
     python3 ARI_consistency_test.py --directory msmc_curve_data/ --spec='regular' --suffix='.txt' --sep='\t' --clust 12 --batches 30 --trials 20 --cutoff_last 1 --cutoff_lastAccumulated 60  --test_runs 30 --accumulative --plot_lightly --real_time --normalize_lambda --log_scale_time --plot_on_log_scale --save_all &", 
     shell=True)
